// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: message.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace SkillBridge.Message
{

    [global::ProtoBuf.ProtoContract()]
    public partial class NUserInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"player")]
        public NPlayerInfo Player { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NPlayerInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"characters")]
        public global::System.Collections.Generic.List<NCharacterInfo> Characters { get; } = new global::System.Collections.Generic.List<NCharacterInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NCharacterInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"config_id")]
        public int ConfigId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"entity_id")]
        public int EntityId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"type")]
        public CharacterType Type { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"class")]
        public CharacterClass Class { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"level")]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"exp")]
        public long Exp { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public NAttributeDynamic attrDynamic { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public int mapId { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"entity")]
        public NEntity Entity { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"gold")]
        public long Gold { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public global::System.Collections.Generic.List<NItemInfo> Items { get; } = new global::System.Collections.Generic.List<NItemInfo>();

        [global::ProtoBuf.ProtoMember(14)]
        public NBagInfo Bag { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public byte[] Equips { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"quests")]
        public global::System.Collections.Generic.List<NQuestInfo> Quests { get; } = new global::System.Collections.Generic.List<NQuestInfo>();

        [global::ProtoBuf.ProtoMember(17, Name = @"friends")]
        public global::System.Collections.Generic.List<NFriendInfo> Friends { get; } = new global::System.Collections.Generic.List<NFriendInfo>();

        [global::ProtoBuf.ProtoMember(18, Name = @"guild")]
        public NGuildInfo Guild { get; set; }

        [global::ProtoBuf.ProtoMember(19, Name = @"ride")]
        public int Ride { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        public global::System.Collections.Generic.List<NSkillInfo> Skills { get; } = new global::System.Collections.Generic.List<NSkillInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NAttributeDynamic : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"HP")]
        public int Hp { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"MP")]
        public int Mp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NItemInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"count")]
        public int Count { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NSkillInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NVector3 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x")]
        public int X { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"y")]
        public int Y { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"z")]
        public int Z { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NBagInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Unlocked { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public byte[] Items { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NStatus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public StatusType Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"action")]
        public StatusAction Action { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"value")]
        public int Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StatusNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"status")]
        public global::System.Collections.Generic.List<NStatus> Status { get; } = new global::System.Collections.Generic.List<NStatus>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NEntity : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"position")]
        public NVector3 Position { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"direction")]
        public NVector3 Direction { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"speed")]
        public int Speed { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NEntitySync : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"event")]
        public EntityEvent Event { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"entity")]
        public NEntity Entity { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"param")]
        public int Param { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NetMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public NetMessageRequest Request { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public NetMessageResponse Response { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NetMessageRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public UserRegisterRequest userRegister { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public UserLoginRequest userLogin { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public UserCreateCharacterRequest createChar { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public UserGameEnterRequest gameEnter { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public UserGameLeaveRequest gameLeave { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public MapCharacterEnterRequest mapCharacterEnter { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public MapEntitySyncRequest mapEntitySync { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public MapTeleportRequest mapTeleport { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public ItemBuyRequest itemBuy { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public ItemEquipRequest itemEquip { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public QuestListRequest questList { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public QuestAcceptRequest questAccept { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public QuestSubmitRequest questSubmit { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public FriendAddRequest friendAddReq { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public FriendAddResponse friendAddRes { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public FriendListRequest friendList { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public FriendRemoveRequest friendRemove { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public TeamInviteRequest teamInviteReq { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        public TeamInviteResponse teamInviteRes { get; set; }

        [global::ProtoBuf.ProtoMember(21)]
        public TeamInfoRequest teamInfo { get; set; }

        [global::ProtoBuf.ProtoMember(22)]
        public TeamLeaveRequest teamLeave { get; set; }

        [global::ProtoBuf.ProtoMember(23)]
        public GuildCreateRequest guildCreate { get; set; }

        [global::ProtoBuf.ProtoMember(24)]
        public GuildJoinRequest guildJoinReq { get; set; }

        [global::ProtoBuf.ProtoMember(25)]
        public GuildJoinResponse guildJoinRes { get; set; }

        [global::ProtoBuf.ProtoMember(26, Name = @"guild")]
        public GuildRequest Guild { get; set; }

        [global::ProtoBuf.ProtoMember(27)]
        public GuildLeaveRequest guildLeave { get; set; }

        [global::ProtoBuf.ProtoMember(28)]
        public GuildListRequest guildList { get; set; }

        [global::ProtoBuf.ProtoMember(29)]
        public GuildAdminRequest guildAdmin { get; set; }

        [global::ProtoBuf.ProtoMember(30, Name = @"chat")]
        public ChatRequest Chat { get; set; }

        [global::ProtoBuf.ProtoMember(50)]
        public SkillCastRequest skillCast { get; set; }

        [global::ProtoBuf.ProtoMember(60)]
        public ArenaChallengeRequest arenaChallengeReq { get; set; }

        [global::ProtoBuf.ProtoMember(61)]
        public ArenaChallengeResponse arenaChallengeRes { get; set; }

        [global::ProtoBuf.ProtoMember(62)]
        public ArenaReadyRequest arenaReady { get; set; }

        [global::ProtoBuf.ProtoMember(63)]
        public StoryStartRequest storyStart { get; set; }

        [global::ProtoBuf.ProtoMember(64)]
        public StoryEndRequest storyEnd { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NetMessageResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public UserRegisterResponse userRegister { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public UserLoginResponse userLogin { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public UserCreateCharacterResponse createChar { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public UserGameEnterResponse gameEnter { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public UserGameLeaveResponse gameLeave { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public MapCharacterEnterResponse mapCharacterEnter { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public MapCharacterLeaveResponse mapCharacterLeave { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public MapEntitySyncResponse mapEntitySync { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public ItemBuyResponse itemBuy { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public ItemEquipResponse itemEquip { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public QuestListResponse questList { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public QuestAcceptResponse questAccept { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public QuestSubmitResponse questSubmit { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public FriendAddRequest friendAddReq { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public FriendAddResponse friendAddRes { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public FriendListResponse friendList { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public FriendRemoveResponse friendRemove { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public TeamInviteRequest teamInviteReq { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        public TeamInviteResponse teamInviteRes { get; set; }

        [global::ProtoBuf.ProtoMember(21)]
        public TeamInfoResponse teamInfo { get; set; }

        [global::ProtoBuf.ProtoMember(22)]
        public TeamLeaveResponse teamLeave { get; set; }

        [global::ProtoBuf.ProtoMember(23)]
        public GuildCreateResponse guildCreate { get; set; }

        [global::ProtoBuf.ProtoMember(24)]
        public GuildJoinRequest guildJoinReq { get; set; }

        [global::ProtoBuf.ProtoMember(25)]
        public GuildJoinResponse guildJoinRes { get; set; }

        [global::ProtoBuf.ProtoMember(26, Name = @"guild")]
        public GuildResponse Guild { get; set; }

        [global::ProtoBuf.ProtoMember(27)]
        public GuildLeaveResponse guildLeave { get; set; }

        [global::ProtoBuf.ProtoMember(28)]
        public GuildListResponse guildList { get; set; }

        [global::ProtoBuf.ProtoMember(29)]
        public GuildAdminResponse guildAdmin { get; set; }

        [global::ProtoBuf.ProtoMember(30, Name = @"chat")]
        public ChatResponse Chat { get; set; }

        [global::ProtoBuf.ProtoMember(50)]
        public SkillCastResponse skillCast { get; set; }

        [global::ProtoBuf.ProtoMember(51)]
        public SkillHitResponse skillHits { get; set; }

        [global::ProtoBuf.ProtoMember(52)]
        public BuffResponse buffRes { get; set; }

        [global::ProtoBuf.ProtoMember(60)]
        public ArenaChallengeRequest arennaChallengeReq { get; set; }

        [global::ProtoBuf.ProtoMember(61)]
        public ArenaChallengeResponse arennaChallengeRes { get; set; }

        [global::ProtoBuf.ProtoMember(62)]
        public ArenaBeginResponse arenaBegin { get; set; }

        [global::ProtoBuf.ProtoMember(63)]
        public ArenaEndResponse arenaEnd { get; set; }

        [global::ProtoBuf.ProtoMember(64)]
        public ArenaReadyResponse arenaReady { get; set; }

        [global::ProtoBuf.ProtoMember(65)]
        public ArenaRoundStarResponse arenaRoundStar { get; set; }

        [global::ProtoBuf.ProtoMember(66)]
        public ArenaRoundEndResponse arenaRoundEnd { get; set; }

        [global::ProtoBuf.ProtoMember(67)]
        public StoryStartResponse storyStart { get; set; }

        [global::ProtoBuf.ProtoMember(68)]
        public StoryEndResponse storyEnd { get; set; }

        [global::ProtoBuf.ProtoMember(100)]
        public StatusNotify statusNotify { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserLoginRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"user")]
        [global::System.ComponentModel.DefaultValue("")]
        public string User { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"passward")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Passward { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserLoginResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"userinfo")]
        public NUserInfo Userinfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserRegisterRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"user")]
        [global::System.ComponentModel.DefaultValue("")]
        public string User { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"passward")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Passward { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserRegisterResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserCreateCharacterRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"class")]
        public CharacterClass Class { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserCreateCharacterResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"characters")]
        public global::System.Collections.Generic.List<NCharacterInfo> Characters { get; } = new global::System.Collections.Generic.List<NCharacterInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserGameEnterRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int characterIdx { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserGameEnterResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"character")]
        public NCharacterInfo Character { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserGameLeaveRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserGameLeaveResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MapCharacterEnterRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int mapId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MapCharacterEnterResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int mapId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"characters")]
        public global::System.Collections.Generic.List<NCharacterInfo> Characters { get; } = new global::System.Collections.Generic.List<NCharacterInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MapCharacterLeaveResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int entityId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MapEntitySyncRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public NEntitySync entitySync { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MapEntitySyncResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<NEntitySync> entitySyncs { get; } = new global::System.Collections.Generic.List<NEntitySync>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MapTeleportRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int teleporterId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ItemBuyRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int shopId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int shopItemId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ItemBuyResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BagSaveRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public NBagInfo BagInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BagSaveResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ItemEquipRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"slot")]
        public int Slot { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int itemId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public bool isEquip { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ItemEquipResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NQuestInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"quest_id")]
        public int QuestId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"quest_guid")]
        public int QuestGuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"status")]
        public QuestStatus Status { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"targets", IsPacked = true)]
        public int[] Targets { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestListRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public QuestListType listType { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestListResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"quests")]
        public global::System.Collections.Generic.List<NQuestInfo> Quests { get; } = new global::System.Collections.Generic.List<NQuestInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestAcceptRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"quest_id")]
        public int QuestId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestAcceptResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"quest")]
        public NQuestInfo Quest { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestSubmitRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"quest_id")]
        public int QuestId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestSubmitResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"quest")]
        public NQuestInfo Quest { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestAbandonRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"quest_id")]
        public int QuestId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestAbandonResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NFriendInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public NCharacterInfo friendInfo { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"status")]
        public int Status { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FriendAddRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"from_id")]
        public int FromId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"from_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FromName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"to_id")]
        public int ToId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"to_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ToName { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FriendAddResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"request")]
        public FriendAddRequest Request { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FriendListRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FriendListResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"friends")]
        public global::System.Collections.Generic.List<NFriendInfo> Friends { get; } = new global::System.Collections.Generic.List<NFriendInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FriendRemoveRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int friendId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FriendRemoveResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"id")]
        public int Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NTeamInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"leader")]
        public int Leader { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"members")]
        public global::System.Collections.Generic.List<NCharacterInfo> Members { get; } = new global::System.Collections.Generic.List<NCharacterInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TeamInviteRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"team_id")]
        public int TeamId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"from_id")]
        public int FromId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"from_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FromName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"to_id")]
        public int ToId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"to_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ToName { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TeamInviteResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"request")]
        public TeamInviteRequest Request { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TeamInfoRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TeamInfoResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"team")]
        public NTeamInfo Team { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TeamLeaveRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"team_id")]
        public int TeamId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int characterId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TeamLeaveResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int characterId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NGuildInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"guild_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string GuildName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int leaderId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string leaderName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"notice")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Notice { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        public int memberCount { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"members")]
        public global::System.Collections.Generic.List<NGuildMemberInfo> Members { get; } = new global::System.Collections.Generic.List<NGuildMemberInfo>();

        [global::ProtoBuf.ProtoMember(8, Name = @"applies")]
        public global::System.Collections.Generic.List<NGuildApplyInfo> Applies { get; } = new global::System.Collections.Generic.List<NGuildApplyInfo>();

        [global::ProtoBuf.ProtoMember(9)]
        public long createTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NGuildMemberInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int characterId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"title")]
        public GuildTitle Title { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"info")]
        public NCharacterInfo Info { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public long joinTime { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public long lastTime { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"status")]
        public int Status { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NGuildApplyInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"guild_id")]
        public int GuildId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int characterId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"class")]
        public int Class { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"level")]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"result")]
        public ApplyResult Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuildCreateRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"guild_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string GuildName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"guild_notice")]
        [global::System.ComponentModel.DefaultValue("")]
        public string GuildNotice { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuildCreateResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public NGuildInfo guildInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuildJoinRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"apply")]
        public NGuildApplyInfo Apply { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuildJoinResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"apply")]
        public NGuildApplyInfo Apply { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuildListRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuildListResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"guilds")]
        public global::System.Collections.Generic.List<NGuildInfo> Guilds { get; } = new global::System.Collections.Generic.List<NGuildInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuildRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuildResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public NGuildInfo guildInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuildLeaveRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuildLeaveResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuildAdminRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"command")]
        public GuildAdminCommand Command { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"target")]
        public int Target { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuildAdminResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"command")]
        public GuildAdminRequest Command { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"channel")]
        public ChatChannel Channel { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"from_id")]
        public int FromId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"from_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FromName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"to_id")]
        public int ToId { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"to_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ToName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"time")]
        public double Time { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"message")]
        public ChatMessage Message { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<ChatMessage> localMessages { get; } = new global::System.Collections.Generic.List<ChatMessage>();

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<ChatMessage> worldMessages { get; } = new global::System.Collections.Generic.List<ChatMessage>();

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<ChatMessage> systemMssages { get; } = new global::System.Collections.Generic.List<ChatMessage>();

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<ChatMessage> privateMessages { get; } = new global::System.Collections.Generic.List<ChatMessage>();

        [global::ProtoBuf.ProtoMember(7)]
        public global::System.Collections.Generic.List<ChatMessage> teamMessages { get; } = new global::System.Collections.Generic.List<ChatMessage>();

        [global::ProtoBuf.ProtoMember(8)]
        public global::System.Collections.Generic.List<ChatMessage> guildMessages { get; } = new global::System.Collections.Generic.List<ChatMessage>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NSkillCastInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int skillId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int casterId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int targetId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"postion")]
        public NVector3 Postion { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"result")]
        public SkillResult Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SkillCastRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public NSkillCastInfo castInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NDamageInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int entityId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"damage")]
        public int Damage { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"crit")]
        public bool Crit { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"will_dead")]
        public bool WillDead { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NSkillHitInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int skillId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int casterId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int hitId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public bool isBullet { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"damage")]
        public global::System.Collections.Generic.List<NDamageInfo> Damages { get; } = new global::System.Collections.Generic.List<NDamageInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SkillCastResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"castInfo")]
        public global::System.Collections.Generic.List<NSkillCastInfo> castInfoes { get; } = new global::System.Collections.Generic.List<NSkillCastInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SkillHitResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"hits")]
        public global::System.Collections.Generic.List<NSkillHitInfo> Hits { get; } = new global::System.Collections.Generic.List<NSkillHitInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NBuffInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int buffId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int buffType { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"action")]
        public BuffACTION Action { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int casterId { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int ownerId { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"damge")]
        public NDamageInfo Damge { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BuffResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"buffs")]
        public global::System.Collections.Generic.List<NBuffInfo> Buffs { get; } = new global::System.Collections.Generic.List<NBuffInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ArenaPlayer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entity_id")]
        public int EntityId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"score")]
        public int Score { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"rank")]
        public int Rank { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ArenaInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"arena_id")]
        public int ArenaId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"red")]
        public ArenaPlayer Red { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"blue")]
        public ArenaPlayer Blue { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ArenaChallengeRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"arena_info")]
        public ArenaInfo ArenaInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ArenaChallengeResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"arena_info")]
        public ArenaInfo ArenaInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ArenaBeginResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"arena_info")]
        public ArenaInfo ArenaInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ArenaEndResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"arena_info")]
        public ArenaInfo ArenaInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ArenaReadyRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int arenaId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"entity")]
        public int Entity { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ArenaReadyResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"round")]
        public int Round { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"arena_info")]
        public ArenaInfo ArenaInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ArenaRoundStarResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"round")]
        public int Round { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"arena_info")]
        public ArenaInfo ArenaInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ArenaRoundEndResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"round")]
        public int Round { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"arena_info")]
        public ArenaInfo ArenaInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StoryStartResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int storyId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int instanceId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StoryStartRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int storyId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int instanceId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StoryEndRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int storyId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int instanceId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StoryEndResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int storyId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"RESULT")]
    public enum Result
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SUCCESS")]
        Success = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"FAILED")]
        Failed = 1,
    }

    [global::ProtoBuf.ProtoContract(Name = @"CHARACTER_TYPE")]
    public enum CharacterType
    {
        Player = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"NPC")]
        Npc = 1,
        Monster = 2,
    }

    [global::ProtoBuf.ProtoContract(Name = @"CHARACTER_CLASS")]
    public enum CharacterClass
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NONE")]
        None = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"WARRIOR")]
        Warrior = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"WIZARD")]
        Wizard = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ARCHER")]
        Archer = 3,
    }

    [global::ProtoBuf.ProtoContract(Name = @"CHARACTER_STATE")]
    public enum CharacterState
    {
        [global::ProtoBuf.ProtoEnum(Name = @"IDLE")]
        Idle = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"MOVE")]
        Move = 1,
    }

    [global::ProtoBuf.ProtoContract(Name = @"ENTITY_EVENT")]
    public enum EntityEvent
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NONE")]
        None = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"IDLE")]
        Idle = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"MOVE_FWD")]
        MoveFwd = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"MOVE_BACK")]
        MoveBack = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"JUMP")]
        Jump = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"RIDE")]
        Ride = 5,
    }

    [global::ProtoBuf.ProtoContract(Name = @"ITEM_TYPE")]
    public enum ItemType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NORMAL")]
        Normal = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"MATERIAL")]
        Material = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"TASK")]
        Task = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"EQUIP")]
        Equip = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"RIDE")]
        Ride = 4,
    }

    [global::ProtoBuf.ProtoContract(Name = @"EQUIP_SLOT")]
    public enum EquipSlot
    {
        [global::ProtoBuf.ProtoEnum(Name = @"WEAPON")]
        Weapon = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCESSORY")]
        Accessory = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"HELMET")]
        Helmet = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"CHEST")]
        Chest = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"SHOULDER")]
        Shoulder = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"PANTS")]
        Pants = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"BOOTS")]
        Boots = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"SLOT_MAX")]
        SlotMax = 7,
    }

    [global::ProtoBuf.ProtoContract(Name = @"STATUS_ACTION")]
    public enum StatusAction
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UPDATE")]
        Update = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ADD")]
        Add = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"DELETE")]
        Delete = 2,
    }

    [global::ProtoBuf.ProtoContract(Name = @"STATUS_TYPE")]
    public enum StatusType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"MONEY")]
        Money = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"EXP")]
        Exp = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"LEVEL")]
        Level = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"SKILL_POINT")]
        SkillPoint = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"ITEM")]
        Item = 4,
    }

    [global::ProtoBuf.ProtoContract(Name = @"STATUS_SOURCE")]
    public enum StatusSource
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UPDATE")]
        Update = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ADD")]
        Add = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"DELETE")]
        Delete = 2,
    }

    [global::ProtoBuf.ProtoContract(Name = @"QUEST_STATUS")]
    public enum QuestStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"IN_PROGRESS")]
        InProgress = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"COMPLATED")]
        Complated = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"FINISHED")]
        Finished = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"FAILED")]
        Failed = 3,
    }

    [global::ProtoBuf.ProtoContract(Name = @"QUEST_LIST_TYPE")]
    public enum QuestListType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ALL")]
        All = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"IN_PROGRESS")]
        InProgress = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"FINISHED")]
        Finished = 2,
    }

    [global::ProtoBuf.ProtoContract(Name = @"GUILD_TITLE")]
    public enum GuildTitle
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NONE")]
        None = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"PRESIDENT")]
        President = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"VICE_PRESIDENT")]
        VicePresident = 2,
    }

    [global::ProtoBuf.ProtoContract(Name = @"APPLY_RESULT")]
    public enum ApplyResult
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NONE")]
        None = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCEPT")]
        Accept = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"REJECT")]
        Reject = 2,
    }

    [global::ProtoBuf.ProtoContract(Name = @"GUILD_ADMIN_COMMAND")]
    public enum GuildAdminCommand
    {
        [global::ProtoBuf.ProtoEnum(Name = @"KICKOUT")]
        Kickout = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"PROMOTE")]
        Promote = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"DEPOST")]
        Depost = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"TRANSFER")]
        Transfer = 4,
    }

    [global::ProtoBuf.ProtoContract(Name = @"CHAT_CHANNEL")]
    public enum ChatChannel
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ALL")]
        All = -1,
        [global::ProtoBuf.ProtoEnum(Name = @"LOCAL")]
        Local = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"WORLD")]
        World = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"SYSTEM")]
        System = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"PRIVATE")]
        Private = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"TEAM")]
        Team = 16,
        [global::ProtoBuf.ProtoEnum(Name = @"GUILD")]
        Guild = 32,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum SkillResult
    {
        [global::ProtoBuf.ProtoEnum(Name = @"OK")]
        Ok = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"Out_Of_Mp")]
        OutOfMp = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"Cool_Down")]
        CoolDown = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"Invalid_Target")]
        InvalidTarget = 3,
        OutOfRange = 4,
        Casting = 5,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum SkillStatus
    {
        None = 0,
        Casting = 1,
        Runing = 2,
    }

    [global::ProtoBuf.ProtoContract(Name = @"Buff_ACTION")]
    public enum BuffACTION
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NONO")]
        Nono = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ADD")]
        Add = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"REMOVE")]
        Remove = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"HIT")]
        Hit = 3,
    }

    [global::ProtoBuf.ProtoContract(Name = @"Arena_Status")]
    public enum ArenaStatus
    {
        None = 0,
        Wait = 1,
        Game = 2,
        Result = 3,
    }

    [global::ProtoBuf.ProtoContract(Name = @"Arena_Round_Status")]
    public enum ArenaRoundStatus
    {
        None = 0,
        Ready = 1,
        Fight = 2,
        Result = 3,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
